FROM node:alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock .yarnrc load-env.sh .env.example.txt ./
RUN yarn install --frozen-lockfile

FROM node:alpine AS runner
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000
ENV DOCKER_CONTAINER 1

ENV NEXT_TELEMETRY_DISABLED 1

CMD ["node_modules/.bin/next", "dev"]