# Install dependencies only when needed
FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock load-env.sh .env.example.txt ./scripts/create-robot.sh ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:alpine AS runner
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/create-robot.sh ./scripts/create-robot.sh

EXPOSE 3000

ENV PORT 3000
ENV DOCKER_CONTAINER 1

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["node_modules/.bin/next", "dev"]