module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_DOMAIN_NAME || 'https://a11ywatch.com',
  priority: 0.7,
  sitemapSize: 5000,
  exclude: [
    '/alerts',
    '/dashboard',
    '/website-analytics',
    '/issues',
    '/scripts',
    '/history',
    '/payments',
    '/website-details/*',
    '/web-issues',
    '/web-view',
    '/web-actions',
    '/web-pages',
    '/settings',
    '/profile',
    '/api',
    '/404',
    '/500',
    '/offline',
    '/website-details',
    '/reports/*',
    '/register?*',
    '/auth-redirect',
    '/auth-redirect?*',
  ],
  sitemapSize: 7000
}
