module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_DOMAIN_NAME || 'https://a11ywatch.com',
  priority: 0.7,
  sitemapSize: 5000,
  exclude: [
    '/alerts',
    '/dashboard',
    '/website-analytics',
    '/issues',
    '/scripts',
    '/history',
    '/payments',
    '/website-details/*',
    '/web-issues',
    '/web-view',
    '/web-actions',
    '/web-pages',
    '/settings',
    '/profile',
    '/api',
    '/404',
    '/500',
    '/offline',
    '/website-details',
    '/reports/*',
    '/register?*',
    '/auth-redirect',
    '/auth-redirect?*',
  ],
  generateRobotsTxt: true,
  sitemapSize: 7000,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: 'Twitterbot',
        allow: ['/*', '/img/*', '/api/og?*', '/pricing?*'],
        disallow: [
          '/*?*',
          '/website-details',
          '/web-view',
          '/web-pages',
          '/settings',
          '/dashboard',
          '/alerts',
          '/profile',
          '/website-analytics',
          '/web-actions',
          '/web-issues',
          '/scripts',
          '/history',
          '/payments',
          '/register?*',
          '/auth-redirect',
          '/auth-redirect?*',
        ],
      },
      {
        userAgent: '*',
        allow: ['/*', '/api/og?*'],
        disallow: [
          '/*?*',
          '/api/*',
          '/website-details',
          '/web-view',
          '/website-details/*',
          '/web-pages',
          '/settings',
          '/iframe/*',
          '/dashboard',
          '/alerts',
          '/profile',
          '/website-analytics',
          '/web-actions',
          '/web-issues',
          '/scripts',
          '/history',
          '/payments',
          '/reports',
          '/reports/*',
          '/register?*',
          '/auth-redirect',
          '/auth-redirect?*',
        ],
      },
    ],
  },
}
