module.exports = {
  baseUrl: process.env.DOMAIN_NAME || 'https://a11ywatch.com',
  ignoredPaths: [
    'alerts',
    'dashboard',
    'analytics',
    'issues',
    'cdn-fix',
    'scripts',
    'history',
    'payments',
    'urgent-issues',
    'website-details',
    'profile',
    'api',
    '404',
    '500',
    'offline',
    'static',
    'img',
    'reports/[...slug]',
  ],
  ignoreIndexFiles: true,
  pagesDirectory: __dirname + '/src/pages',
  nextConfigPath: __dirname + '/next.config.js',
  targetDirectory: 'public/',
  ignoredExtensions: ['png', 'jpg', 'webp', 'json', 'js', 'map', 'woff2'],
}
